#!/usr/bin/env php
<?php

/**
 * Yii console bootstrap file.
 *
 * @link https://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license https://www.yiiframework.com/license/
 */

declare(strict_types=1);

use yii\console\Application;

if (
    !file_exists(__DIR__ . '/REVISION') &&
    !file_exists(__DIR__ . '/.production')
) {
    define('YII_DEBUG', true);
    define('YII_ENV', 'dev');
}

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

exit(
    (new Application(require __DIR__ . '/config/console.php'))->run()
);
